FB8-251: Throw exit 1 in case of BoringSSL compilation failure

diff --git a/local/build-binary b/local/build-binary
--- a/local/build-binary
+++ b/local/build-binary
@@ -91,7 +91,10 @@ if [[ ${WITH_BORINGSSL} == "true" ]]; then
         cp crypto/libcrypto.a ${WORKDIR}/boringssl_bin/lib/libcrypto_pic.a
         cp ssl/libssl.a ${WORKDIR}/boringssl_bin/lib/libssl_pic.a
         cp -r ../include ${WORKDIR}/boringssl_bin/
-        CMAKE_OPTS+=" -DWITH_SSL=system -DCMAKE_PREFIX_PATH=${WORKDIR}/boringssl_bin"        
+        CMAKE_OPTS+=" -DWITH_SSL=system -DCMAKE_PREFIX_PATH=${WORKDIR}/boringssl_bin"
+    else
+        echo "BoringSSL compilation failed."
+        exit 1
     fi
 fi
 
