JEN-971 Jenkins cannot parse MTR test results properly after 5.7.24 upstream merge [+] added regexp to filter lines related to tests

diff --git a/local/test-binary b/local/test-binary
--- a/local/test-binary
+++ b/local/test-binary
@@ -23,7 +23,33 @@ TOKUDB_PLUGIN=$(find $WORKDIR_ABS -type f -name 'ha_tokudb.so')
 HOTBACKUP_LIB=$(find $WORKDIR_ABS -type f -name 'libHotBackup.so')
 HOTBACKUP_PLUGIN=$(find $WORKDIR_ABS -type f -name 'tokudb_backup.so')
 JEMALLOC=$(find /lib* /usr/lib* /usr/local/lib* -type f -name 'libjemalloc.so*' | head -n1)
-
+#
+function process_mtr_output {
+# parameters are:
+  local TESTSUITE=${1}
+  local INFILE=${2}
+  local OUTFILE=${3}
+  egrep -o '[[:alpha:]]+(_[[:alnum:]]+)?(\.\/)?.*\[.*\].*' ${INFILE} | sort | \
+  gawk 'BEGIN { print "<testsuite name=\"@@TESTSUITE@@\" tests=\"@@PASSED@@\" failures=\"@@FAILURES@@\" disabled=\"@@DISABLED@@\" skipped=\"@@SKIPPED@@\">" }
+  /\[.*pass \]/ { printf "\t<testcase name=\"%s\" time=\"%.3f\"></testcase>\n", $1" "$2, $NF/1000.0 }
+  /\[ disabled \]/       { printf "\t<testcase name=\"%s\"><skipped/></testcase>\n", $1" "$2 }
+  /\[ skipped \]/       { printf "\t<testcase name=\"%s\"><skipped/></testcase>\n", $1" "$2 }
+  /\[.*fail \]/ { printf "\t<testcase name=\"%s\"><failure/></testcase>\n", $1" "$2 }
+  END { print "</testsuite>" }' > ${OUTFILE}
+#
+  PASSED=$(. grep -c '\[.*pass \]'    ${INFILE} ||: )
+  FAILURES=$(grep -c '\[.*fail \]'    ${INFILE} ||: )
+  DISABLED=$(grep -c '\[ disabled \]' ${INFILE} ||: )
+  SKIPPED=$( grep -c '\[ skipped \]'  ${INFILE} ||: )
+#
+  sed -i.bak -e "s:@@TESTSUITE@@:${TESTSUITE}:g" ${OUTFILE}
+  sed -i.bak -e "s:@@PASSED@@:${PASSED}:g" ${OUTFILE}
+  sed -i.bak -e "s:@@FAILURES@@:${FAILURES}:g" ${OUTFILE}
+  sed -i.bak -e "s:@@DISABLED@@:${DISABLED}:g" ${OUTFILE}
+  sed -i.bak -e "s:@@SKIPPED@@:${SKIPPED}:g" ${OUTFILE}
+  sed -i.bak -e "s: \[::g" ${OUTFILE}
+}
+#
 if [[ "${CMAKE_BUILD_TYPE}" = "Debug" ]]; then
     MTR_ARGS+=" --debug-server"
 fi
@@ -67,7 +93,7 @@ if [[ "${DEFAULT_TESTING}" != "no" ]]; then
         --testcase-timeout=450 \
         | tee ${WORKDIR_ABS}/mtr.output \
         || status=$?
-    awk 'BEGIN { print "<testsuite name=\"MySQL\">" } /^([[:alnum:]]+).*[\[] (retry-)?pass [\]](.*)/ { print "<testcase name=\""$1"\" time=\"" $6/1000 "\"/>" } /^(.*) .*\[ skipped \]/ { print "<testcase name=\""$1"\"><skipped/></testcase>" } /^(.*) .*\[ (retry-)?fail \]/ { print "<testcase name=\""$1"\"><failure/></testcase>" } /^MTR\47s internal check of the test case \47(.*)\47 failed/ { print "<testcase name=\"testcase-check-"$8"\"><failure/></testcase>" } END { print "</testsuite>" }' < ${WORKDIR_ABS}/mtr.output > $WORKDIR_ABS/junit.xml
+    process_mtr_output MySQL "${WORKDIR_ABS}/mtr.output" "$WORKDIR_ABS/junit.xml"
 fi
 
 
@@ -88,7 +114,7 @@ if [[ "$HOTBACKUP_TESTING" != "no" ]] && [[ -n "${TOKUDB_PLUGIN}" ]] && [[ -n "$
         --suite tokudb.backup \
         | tee ${WORKDIR_ABS}/tokudb_hotbackup.output \
         || true
-    awk 'BEGIN { print "<testsuite name=\"Percona Server - TokuDB HotBackup\">" } /^([[:alnum:]]+).*[\[] (retry-)?pass [\]](.*)/ { print "<testcase name=\""$1"\" time=\"" $6/1000 "\"/>" } /^(.*) .*\[ skipped \]/ { print "<testcase name=\""$1"\"><skipped/></testcase>" } /^(.*) .*\[ (retry-)?fail \]/ { print "<testcase name=\""$1"\"><failure/></testcase>" } /^MTR\47s internal check of the test case \47(.*)\47 failed/ { print "<testcase name=\"testcase-check-"$8"\"><failure/></testcase>" } END { print "</testsuite>" }' < ${WORKDIR_ABS}/tokudb_hotbackup.output > ${WORKDIR_ABS}/junit_tokudb_hotbackup.xml
+    process_mtr_output "Percona Server - TokuDB HotBackup" "${WORKDIR_ABS}/tokudb_hotbackup.output" "${WORKDIR_ABS}/junit_tokudb_hotbackup.xml"
 fi
 
 # if there's tokudb plugin compiled run tokudb tests else exit with previous status
@@ -112,7 +138,7 @@ if [[ "${TOKUDB_ENGINES_MTR}" = "yes" ]] && [[ -n "${TOKUDB_PLUGIN}" ]]; then
             --mysqld=--loose-tokudb_auto_analyze=0 --mysqld=--loose-tokudb_analyze_in_background=false \
             ${TOKUDB_ENGINES_MTR_ARGS} \
             2>&1 | tee ${WORKDIR_ABS}/tokudb.output || true
-    awk 'BEGIN { print "<testsuite name=\"Percona Server - TokuDB\">" } /^([[:alnum:]]+).*[\[] (retry-)?pass [\]](.*)/ { print "<testcase name=\""$1"\" time=\"" $6/1000 "\"/>" } /^(.*) .*\[ skipped \]/ { print "<testcase name=\""$1"\"><skipped/></testcase>" } /^(.*) .*\[ (retry-)?fail \]/ { print "<testcase name=\""$1"\"><failure/></testcase>" } /^MTR\47s internal check of the test case \47(.*)\47 failed/ { print "<testcase name=\"testcase-check-"$8"\"><failure/></testcase>" } END { print "</testsuite>" }' < ${WORKDIR_ABS}/tokudb.output > ${WORKDIR_ABS}/junit_tokudb.xml
+    process_mtr_output "Percona Server - TokuDB" "${WORKDIR_ABS}/tokudb.output" "${WORKDIR_ABS}/junit_tokudb.xml"
 fi
 
 exit $status
