JEN-971 [*] backported mtr parser function from 5.7

diff --git a/local/test-binary b/local/test-binary
--- a/local/test-binary
+++ b/local/test-binary
@@ -29,17 +29,30 @@ MTR_ARGS+=" --timestamp --non-parallel-test"
 ##
 function process_mtr_output {
 # parameters are:
-  local TESTNAME=$1
-  local INFILE=$2
-  local OUTFILE=$3
-  echo  "<testsuite name=\"${TESTNAME}\">" > ${OUTFILE}
-  #
-  awk '/^([[:alnum:]]+).*[\[] (retry-)?pass [\]](.*)/                 { print "<testcase name=\""$3"\" time=\"" $8/1000 "\"/>" }
-       /^(.*) .*\[ skipped \]/                                        { print "<testcase name=\""$3"\"><skipped/></testcase>" }
-       /^(.*) .*\[ (retry-)?fail \]/                                  { print "<testcase name=\""$3"\"><failure/></testcase>" }
-       /^MTR\47s internal check of the test case \47(.*)\47 failed/   { print "<testcase name=\"testcase-check-"$8"\"><failure/></testcase>" }' < ${INFILE} >> ${OUTFILE}
-  #
-  echo  "</testsuite>" >> ${OUTFILE}
+  local TESTSUITE=${1}
+  local INFILE=${2}
+  local OUTFILE=${3}
+  egrep -o '[[:alpha:]]+(_[[:alnum:]]+)?(\.\/)?.*\[.*\].*' ${INFILE} | sort | \
+  gawk 'BEGIN { print "<testsuite name=\"@@TESTSUITE@@\" tests=\"@@PASSED@@\" failures=\"@@FAILURES@@\" disabled=\"@@DISABLED@@\" skipped=\"@@SKIPPED@@\">" }
+  /\[.*pass \]/ { printf "\t<testcase name=\"%s\" time=\"%.3f\"></testcase>\n", $1" "$2, $NF/1000.0 }
+  /\[ disabled \]/ { printf "\t<testcase name=\"%s\"><skipped/></testcase>\n", $1" "$2 }
+  /\[ skipped \]/  { printf "\t<testcase name=\"%s\"><skipped/></testcase>\n", $1" "$2 }
+  /\[.*fail \]/    { printf "\t<testcase name=\"%s\"><failure/></testcase>\n", $1" "$2 }
+  END { print "</testsuite>" }' > ${OUTFILE}.tmp
+  gawk '!seen[$0]++' < ${OUTFILE}.tmp > ${OUTFILE}
+  rm -f ${OUTFILE}.tmp
+#
+  PASSED=$(grep -c 'time=' ${OUTFILE} ||:)
+  FAILURES=$(grep -c '<failure/>' ${OUTFILE} ||:)
+  DISABLED=$(grep -c '\[ disabled \]' ${INFILE} ||:)
+  SKIPPED=$(grep -c '\[ skipped \]' ${INFILE} ||:)
+#
+  sed -i.bak -e "s:@@TESTSUITE@@:${TESTSUITE}:g" ${OUTFILE}
+  sed -i.bak -e "s:@@PASSED@@:${PASSED}:g" ${OUTFILE}
+  sed -i.bak -e "s:@@FAILURES@@:${FAILURES}:g" ${OUTFILE}
+  sed -i.bak -e "s:@@DISABLED@@:${DISABLED}:g" ${OUTFILE}
+  sed -i.bak -e "s:@@SKIPPED@@:${SKIPPED}:g" ${OUTFILE}
+  sed -i.bak -e "s: \[::g" ${OUTFILE}
 }
 ##
 #
@@ -89,7 +102,7 @@ if [[ "${DEFAULT_TESTING}" != "no" ]]; then
         --suite-timeout=9999 \
         --testcase-timeout=${TESTCASE_TIMEOUT} \
         | tee ${WORKDIR_ABS}/mtr.output || status=$?
-    process_mtr_output MySQL "${WORKDIR_ABS}"/mtr.output "${WORKDIR_ABS}"/junit.xml
+    process_mtr_output MySQL "${WORKDIR_ABS}/mtr.output" "${WORKDIR_ABS}/junit.xml"
 fi
 
 
@@ -109,7 +122,7 @@ if [[ "$HOTBACKUP_TESTING" != "no" ]] && [[ -n "${TOKUDB_PLUGIN}" ]] && [[ -n "$
         --mysqld-env="LD_PRELOAD=${MYSQLD_ENV}" \
         --suite tokudb.backup \
         | tee ${WORKDIR_ABS}/tokudb_hotbackup.output || true
-    process_mtr_output "Percona Server - TokuDB HotBackup" "${WORKDIR_ABS}"/tokudb_hotbackup.output "${WORKDIR_ABS}"/junit_tokudb_hotbackup.xml
+    process_mtr_output "Percona Server - TokuDB HotBackup" "${WORKDIR_ABS}/tokudb_hotbackup.output" "${WORKDIR_ABS}/junit_tokudb_hotbackup.xml"
 fi
 
 # if there's tokudb plugin compiled run tokudb tests else exit with previous status
@@ -133,7 +146,7 @@ if [[ "${TOKUDB_ENGINES_MTR}" = "yes" ]] && [[ -n "${TOKUDB_PLUGIN}" ]]; then
             --mysqld=--loose-tokudb_auto_analyze=0 --mysqld=--loose-tokudb_analyze_in_background=false \
             ${TOKUDB_ENGINES_MTR_ARGS} \
             2>&1 | tee ${WORKDIR_ABS}/tokudb.output || true
-    process_mtr_output "Percona Server - TokuDB" "${WORKDIR_ABS}"/tokudb.output "${WORKDIR_ABS}"/junit_tokudb.xml
+    process_mtr_output "Percona Server - TokuDB" "${WORKDIR_ABS}/tokudb.output" "${WORKDIR_ABS}/junit_tokudb.xml"
 fi
 
 exit $status
